#!/bin/zsh

# Safe dmenu defaults. Add to whatever cool patched version of dmenu you have.
DMENU="dmenu -i -z"

# Alternative ssh known_hosts file, if you need that for whatever reason
# SSHMUX_KNOWN_HOSTS="$HOME/ssh/hax0r/known_hosts"

# Terminal spawner command for dmenu_sshmux
# SSHMUX_CMD="xterm -t sshmux %q"
